### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by BLYKIM** [aicers/giganto-client#2]
아직 giganto에서 merge되지 않은 수정사항이 올라오면
통합하여 0.2.0으로 Release 합니다.

**Comment by sehkone** [comment]
@BLYKIM @kimhanbeom

테스트는 브랜치로 하고 PR은 릴리즈 버전을 사용해야 합니다. 따라서, 일제히 release하는 개념이 아니고, 의존성이 낮은 것부터 순서대로 release를 하는 것입니다.

**Comment by sehkone** [comment]
브랜치들로 테스트가 되었다면, release를 빨리 하세요.
