### ISSUE TITLE
Confirmation for requesting a list of events

### ISSUE THREAD

**Issue by minshao** [aicers/giganto-client#32]
To my understanding of the code, to ask for a list of events: 
```Rust
let msg_code = MessageCode::RawData;

let kind = "some_kind".to_string();

let input: Vec<(String, Vec<i64>)> = vec![];

let req_data =  RequestRawData {
    kind,
    input,
}
```
And the response would be, assuming `request_giganto` sends the request properly and receives all the response data: 
```Rust
let recv_events: Vec<(String, Vec<T>)> = request_giganto(msg_code, &req_data).await?;
// note that this is a pseudo code, just to give an example
```

And given the above:

- [x] In `giganto-client/src/publish.rs`, `receive_raw_events` should return `Vec<(i64, String, Vec<T>)>`, related function `send_raw_events` etc should have modification accordingly.
- [x] Add `kind` field for `TimeSeries` data, and merge `RequestRange` and `RequestTimeSeriesRange`
- [x] Allow `RequestRawData` to get events from TimeSeries db.

**Comment by syncpark** [comment]
@kimhanbeom
Related to the first issue of above:
 * in `Giganto/src/publish/tests.rs`, and in `giganto-client/src/publish.rs`, the function `receive_raw_events(...)`
 * Please modify the response type to `Vec<(i64, String, Vec<T>)>` (add event_id in the first place of tuple). And please check all code that call this function.

And please write more description about the QUIC API, especially example code to call the API

**Comment by syncpark** [comment]
@minshao 
Related to the second issue of above:
As you can see in `Giganto/src/publish.rs`, `REconvergeKindType` is used only for `MessageCode::Log` and `MessageCode::RawData`. And it's not used for `MessageCode::PeriodicTimeSeries`.

You should use `RequestTimeSeriesRange` structure to retrieve `TimeSeries` events.
```rust
pub struct RequestTimeSeriesRange {
    pub source: String, //sampling policy id
    pub start: i64,
    pub end: i64,
    pub count: usize,
}

        let msg_code = MessageCode::PeriodicTimeSeries;
        let req_data = RequestTimeSeriesRange {
             source: policy_id.to_string(),
             start: ...,
             end: ...,
             count: ...
        };
```

**Comment by minshao** [comment]
> You should use `RequestTimeSeriesRange` structure to retrieve `TimeSeries` events.

It was meant for requesting `Giganto` for a list of outlier events that are of type `Vec<(String, Vec<i64>)>`, while it's possible to convert each event into a range request and use `RequestTimeSeriesRange`, it will be very inefficient and cumbersome. The solution that I proposed is to let `RequestRawData` handling requesting a list of time series data. That being said, it's also acceptable to have a new request `RequestTimeSeriesData` (or some other preferred name) in `Giganto` to handle corresponding request for time series data.

As for adding `kind` to `TimeSeries` db, I'm all for it. Just want to mention that, after adding `kind` field, `RequestTimeSeriesRange` and `RequestRange` would be identical, and I would suggest merging the two. And make `kind` an `enum` instead of String, something like the following: 
``` Rust
  enum DataKind {
    Raw(REconvergeKindType),
    Timeseries(TimeSeriesKind),
  }
  enum RawKind {
    ...
  }
```

**Comment by syncpark** [comment]
@minshao Ok now I understand what you said.

@kimhanbeom 
As a summary, you have two things to change.
1. You have to merge `RequestRange` and `RequestTimeSeriesRange` structure. 
2. Change `RequestRawData` to get events from `TimeSeries` db.

**Comment by msk** [comment]
This issue hasn't seen an update for a few weeks and this lack of development has started to have a direct impact on our work with models in REconverge.

Specifically, we currently have a branch in progress that reduces the size of a model stored in the database. This branch relies on the APIs outlined in the comment above, which we need implemented in `giganto-client`. However, as these APIs are yet to be realized in `giganto-client`, we're unable to merge this branch into our main codebase. As a consequence, we're continuously required to rebase this branch with every change made to REconverge. This practice is causing significant maintenance overhead and preventing us from making further improvements and adding new features to models.

In addition to this, the current format of a model in the database is opaque, necessitating intricate migration logic if the format is to be changed. With all these issues combined, we find it essential to have this issue addressed before we proceed with any alterations to the models.

The specific issues we'd like to see addressed are:

1. In `giganto-client/src/publish.rs`, `receive_raw_events` should return `Vec<(i64, String, Vec<T>)>`. Related functions, such as `send_raw_events`, should also be adjusted accordingly.
2. The addition of a `kind` field for `TimeSeries` data, alongside the merging of `RequestRange` and `RequestTimeSeriesRange`.
3. The ability for `RequestRawData` to fetch events from the TimeSeries database.

Resolving these issues swiftly would immensely facilitate our work on improvements related to models in REconverge. 

Your prompt attention to these matters would be highly appreciated, and it would go a long way in enhancing the functionality and efficiency of our work.

**Comment by kimhanbeom** [comment]
Close this issue as the implementation of this issue has been applied to `giganto-client` and `giganto`
